/* Final C algorithm for the GCC -O2 reference and native cross-checks.
 * This is Stage 3's coordinate/FIFO/IDA* algorithm using an explicit stack.
 * Quarter-turn tables are generated by the unchanged Stage 3 table builder. */
#include <stdint.h>
#include "build/tables.h"
static const uint16_t *const pt[3] = {
    permutation_turns, permutation_turns + 5040, permutation_turns + 10080
};
static const uint16_t *const ot[3] = {
    orientation_turns, orientation_turns + 729, orientation_turns + 1458
};
static uint8_t pd[5040], od[729];
static uint16_t queue[5040];
typedef struct {
    uint32_t p, o, np, no, face, turn, previous, unused;
} target_frame;
static target_frame frames[12];
static uint8_t result_path[12];

static int target_bfs(unsigned count, const uint16_t *const *turns,
                      uint8_t *distance, unsigned goal)
{
    unsigned head = 0, tail = 1;
    for (unsigned i = 0; i < count; ++i) distance[i] = 255;
    distance[goal] = 0;
    queue[0] = (uint16_t)goal;
    while (head < tail) {
        unsigned here = queue[head++];
        for (unsigned face = 0; face < 3; ++face) {
            unsigned there = here;
            for (unsigned turn = 0; turn < 3; ++turn) {
                there = turns[face][there];
                if (distance[there] == 255) {
                    distance[there] = (uint8_t)(distance[here] + 1);
                    queue[tail++] = (uint16_t)there;
                }
            }
        }
    }
    return tail == count;
}

#ifdef COUNT_NODES
static uint64_t attempted_children, accepted_children, exhausted_frames;
#define COUNT(x) (++(x))
#else
#define COUNT(x) ((void)0)
#endif

static int solve_coordinates(unsigned gp, unsigned go)
{
    if (!target_bfs(5040, pt, pd, gp) || !target_bfs(729, ot, od, go)) return -1;
    unsigned first = pd[0] > od[0] ? pd[0] : od[0];
    for (unsigned bound = first; bound <= 11; ++bound) {
        unsigned depth = 0;
        frames[0] = (target_frame){0, 0, 0, 0, 0, 0, 3, 0};
        if (gp == 0 && go == 0) return 0;
        for (;;) {
            target_frame *f = &frames[depth];
            if (depth == bound || f->face == 3) {
                COUNT(exhausted_frames);
                if (depth == 0) break;
                --depth;
                continue;
            }
            unsigned face = f->face;
            if (face == f->previous) { ++f->face; continue; }
            COUNT(attempted_children);
            unsigned np = pt[face][f->np], no = ot[face][f->no];
            unsigned turn = f->turn++;
            if (f->turn == 3) {
                ++f->face; f->turn = 0; f->np = f->p; f->no = f->o;
            } else { f->np = np; f->no = no; }
            unsigned h = pd[np] > od[no] ? pd[np] : od[no];
            if (depth + 1 + h > bound) continue;
            COUNT(accepted_children);
            result_path[depth++] = (uint8_t)((face << 1) + face + turn);
            if (np == gp && no == go) return (int)depth;
            frames[depth] = (target_frame){np, no, np, no, 0, 0, face, 0};
        }
    }
    return -1;
}

static int target_parse(const char *input, unsigned *gp, unsigned *go)
{
    unsigned seen = 0, p = 0, o = 0, sum = 0;
    static const unsigned weights[6] = {720,120,24,6,2,1};
    for (unsigned i = 0; i < 7; ++i) {
        unsigned digit = (unsigned)(unsigned char)input[i] - '1';
        if (digit >= 7 || (seen & (1u << digit))) return 0;
        seen |= 1u << digit;
    }
    for (unsigned i = 0; i < 6; ++i)
        for (unsigned j = i + 1; j < 7; ++j)
            if (input[j] < input[i]) p += weights[i];
    for (unsigned i = 0; i < 7; ++i) {
        unsigned digit = (unsigned)(unsigned char)input[i+7] - '1';
        if (digit >= 3) return 0;
        sum += digit;
        if (i < 6) o = (o << 1) + o + digit;
    }
    while (sum >= 3) sum -= 3;
    if (sum || input[14]) return 0;
    *gp = p; *go = o;
    return 1;
}

static int target_validate(unsigned gp, unsigned go, unsigned length)
{
    while (length) {
        unsigned move = result_path[--length], face = 0;
        while (move >= 3) { move -= 3; ++face; }
        for (unsigned n = 3 - move; n; --n) { gp = pt[face][gp]; go = ot[face][go]; }
    }
    return gp == 0 && go == 0;
}
